apiVersion: v1
kind: ConfigMap
metadata:
  name: funny-pokedex-config
data:
  SERVER_PORT: "5000"
  SPRING_PROFILES_ACTIVE: prod
  LOG_LEVEL: INFO

  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  REDIS_TIMEOUT: 5s

  POKEAPI_BASE_URL: https://pokeapi.co/api/v2
  FUNTRANSLATIONS_BASE_URL: https://api.funtranslations.mercxry.me/v1/translate
  FUNTRANSLATIONS_SHAKESPEARE_PATH: /shakespeare
  FUNTRANSLATIONS_YODA_PATH: /yoda

  CACHE_TTL: 24h
  CACHE_NAME_POKEMON: pokemon
  CACHE_NAME_POKEMON_TRANSLATED: pokemon-translated

  RATE_LIMIT_FOR_PERIOD: "20"
  RATE_LIMIT_REFRESH_PERIOD: 1m
  RATE_LIMIT_TIMEOUT: "0"

  POKEAPI_RETRY_MAX_ATTEMPTS: "3"
  POKEAPI_RETRY_WAIT: 500ms
  POKEAPI_CB_SLIDING_WINDOW_SIZE: "10"
  POKEAPI_CB_FAILURE_RATE_THRESHOLD: "50"
  POKEAPI_CB_WAIT_OPEN: 30s

  FUNTRANSLATIONS_RETRY_MAX_ATTEMPTS: "3"
  FUNTRANSLATIONS_RETRY_WAIT: 500ms
  FUNTRANSLATIONS_CB_SLIDING_WINDOW_SIZE: "10"
  FUNTRANSLATIONS_CB_FAILURE_RATE_THRESHOLD: "50"
  FUNTRANSLATIONS_CB_WAIT_OPEN: 60s

  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
