apiVersion: apps/v1
kind: Deployment
metadata:
  name: funny-pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funny-pokedex
  template:
    metadata:
      labels:
        app: funny-pokedex
    spec:
      containers:
        - name: funny-pokedex
          image: funny-pokedex:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: funny-pokedex-config
