apiVersion: apps/v1
kind: Deployment
metadata:
  name: funny-pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funny-pokedex
  template:
    metadata:
      labels:
        app: funny-pokedex
    spec:
      containers:
        - name: funny-pokedex
          image: funny-pokedex:latest
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          volumeMounts:
            - name: config-volume
              mountPath: /config
          command: ["java", "-jar", "app.jar", "--spring.config.additional-location=file:/config/application-prod.properties"]
      volumes:
        - name: config-volume
          configMap:
            name: funny-pokedex-config
            items:
              - key: application-prod.properties
                path: application-prod.properties
